global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
  - records.yml
  - alerts.yml

scrape_configs:
  - job_name: "ec2-nodes"
    ec2_sd_configs:
      - region: us-east-1
        access_key: {{ACCESS_KEY}}
        secret_key: {{ACCESS_SECRET}}
        port: 9100
        filters:
          - name: tag:Monitor
            values: ["yes"]
